# Generated by Django 5.2.3 on 2025-09-17 17:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-\\.]+$', 'Only letters, numbers, spaces, hyphens and periods allowed')])),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('sports', 'Sports'), ('theater', 'Theater'), ('conference', 'Conference'), ('festival', 'Festival'), ('other', 'Other')], max_length=20)),
                ('stadium_name', models.CharField(max_length=255)),
                ('stadium_image', models.URLField(max_length=500)),
                ('event_logo', models.URLField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('normal_service_charge', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reseller_service_charge', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('sold_tickets', models.PositiveIntegerField(default=0)),
                ('total_sold_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('superadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Enter a valid hex color code')])),
                ('lower_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('upper_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='events.event')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_id'], name='events_even_event_i_f8741a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'time'], name='events_even_date_3a55f7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='events_even_categor_aca11d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsection',
            unique_together={('event', 'name')},
        ),
    ]
