# Generated by Django 5.2.3 on 2025-12-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="sports_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="stadium_svg_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emiratesStadium", "Emirates Stadium"),
                    ("villaParkStadium", "Villa Park Stadium"),
                    ("oldTraffordStadium", "Old Trafford"),
                    ("anfieldStadium", "Anfield Stadium"),
                    ("ellandStadium", "Elland Road"),
                    ("tottenhamHotspurStadium", "Tottenham Hotspur Stadium"),
                    ("hillDickinsonStadium", "Hill Dickinson Stadium"),
                    ("sanSiro", "San Siro"),
                    ("molineux", "Molineux Stadium"),
                    ("cravenCottage", "Craven Cottage"),
                    ("etihadStadium", "Etihad Stadium"),
                    ("santiagoBernabeuStadium", "Santiago Bernabéu Stadium"),
                    ("riyadhMetropolitanoStadium", "Riyadh Metropolitano Stadium"),
                ],
                help_text="SVG key for interactive stadium map. Leave blank if no SVG available.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="team",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
