# Generated by Django 5.2.3 on 2026-03-17 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_comprehensive_schema_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('team', 'Team'), ('tournament', 'Tournament'), ('other', 'Other')], default='other', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_categor_aca11d_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category_legacy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sports_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stadium_svg_key',
            field=models.CharField(blank=True, choices=[('emiratesStadium', 'Emirates Stadium'), ('villaParkStadium', 'Villa Park Stadium'), ('oldTraffordStadium', 'Old Trafford'), ('anfieldStadium', 'Anfield Stadium'), ('ellandStadium', 'Elland Road'), ('tottenhamHotspurStadium', 'Tottenham Hotspur Stadium'), ('hillDickinsonStadium', 'Hill Dickinson Stadium'), ('sanSiro', 'San Siro'), ('molineux', 'Molineux Stadium'), ('cravenCottage', 'Craven Cottage'), ('etihadStadium', 'Etihad Stadium'), ('santiagoBernabeuStadium', 'Santiago Bernabéu Stadium'), ('riyadhMetropolitanoStadium', 'Riyadh Metropolitano Stadium'), ('gtechCommunityStadium', 'Gtech Community Stadium'), ('stamfordBridge', 'Stamford Bridge'), ('turfMoorStadium', 'Turf Moor Stadium'), ('queenElizabethOlympicPark', 'Queen Elizabeth Olympic Park'), ('selhurstPark', 'Selhurst Park'), ('celticStadium', 'Celtic Stadium')], help_text='SVG key for interactive stadium map. Leave blank if no SVG available.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='normal_service_charge',
            field=models.DecimalField(decimal_places=2, help_text='Service charge for normal users (no maximum limit)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='reseller_service_charge',
            field=models.DecimalField(decimal_places=2, help_text='Service charge for resellers (no maximum limit)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type', 'country')},
        ),
    ]
