# Generated by Django 5.2.3 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('team', 'Team'), ('tournament', 'Tournament'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type', 'country')},
        ),
    ]
