# Generated by Django 5.2.3 on 2025-11-20 05:47

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='upload_file',
            field=models.FileField(blank=True, null=True, storage=tickets.models.PdfStorage(), upload_to=''),
        ),
    ]
