# Generated by Django 5.2.3 on 2025-12-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bundle_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups tickets that must be sold together', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sell_together',
            field=models.BooleanField(default=False, help_text='If checked, all tickets in this bundle must be purchased together'),
        ),
    ]
