# Generated by Django 5.2.3 on 2026-03-04 20:18

import django.contrib.postgres.fields
import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_populate_ticket_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bundle_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups tickets that must be sold together', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sell_together',
            field=models.BooleanField(default=False, help_text='If checked, all tickets in this bundle must be purchased together'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Custom order number for display (e.g., Order# 286884113)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='revolut_checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='revolut_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket_benefits_and_Restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket_file',
            field=models.FileField(blank=True, help_text='PDF or image file of the ticket', null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket_seats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), help_text='Comma separated seat numbers.', size=None),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='benefits_and_Restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('select_features_disclosures', 'Select features & disclosures'), ('restricted_view', 'Restricted view (printed on ticket)'), ('child_16_under', 'Child ticket (ages 16 and under)*'), ('child_18_under', 'Child ticket (ages 18 and under)*'), ('junior_21_under', 'Junior ticket (ages 21 and under)'), ('senior_61_older', 'Senior ticket (61 and older)'), ('away_supporters_only', 'Away Supporters Only'), ('home_supporters_only', 'Home Supporters Only'), ('early_access', 'Early Access'), ('vip_lounge_access', 'Vip Lounge Access'), ('parking_pass', 'Parking Pass'), ('full_suite_not_shared', 'Full Suite (not shared)'), ('full_suite_shared', 'Full Suite (Shared)'), ('unlimited_food_drinks', 'Includes unlimited food and drinks'), ('limited_complimentary_food_drinks', 'Includes limited complimentary food and drinks'), ('food_drink_voucher', 'Food and drink voucher included'), ('food_drink_available_purchase', 'Food and drink Available for Purchase'), ('pregame_food_beverage', 'Includes pregame food and beverage'), ('free_halftime_drinks', 'Free Halftime drinks'), ('complimentary_matchday_programme', 'Complimentary matchday programme'), ('padded_seats', 'Padded Seats'), ('standing_only', 'Standing Only'), ('next_to_players_entrance', "Next to players' entrance"), ('validate', 'Validate')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Comma separated seat numbers.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, help_text='Custom ticket number for display (e.g., Ticket# 524891234)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upload_file',
            field=models.FileField(blank=True, null=True, storage=tickets.models.PdfStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_reserved', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(db_index=True, default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='tickets.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'is_expired'], name='tickets_tic_ticket__800a4a_idx'), models.Index(fields=['expires_at'], name='tickets_tic_expires_5be74a_idx'), models.Index(fields=['order'], name='tickets_tic_order_i_70e16b_idx')],
            },
        ),
    ]
