# Generated by Django 5.2.3 on 2026-03-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_populate_custom_ids'),
        ('tickets', '0010_populate_order_numbers'),
    ]

    operations = [
    ]
